### ISSUE TITLE
Use Robust Wait Strategies

### ISSUE THREAD

**Issue by sadeesh-sdet** [tejaswinidevi/ParaBank#5]
I see there are many static waits implemented in this file like [this](https://github.com/tejaswinidevi/ParaBank/blob/master/src/test/java/com/paraBanking/stepDefinitions/ParaBankStepDefinitions.java#L151). If i execute the test in in-consistent network latency, there are many chances that these tests will show negative results. Please refer [this](https://www.selenium.dev/documentation/webdriver/waits/#fluentwait).

**Comment by tejaswinidevi** [comment]
used a mix of webdriver wait, fluent wait and implicit wait for consistency.
