### ISSUE TITLE
Use the customised selectors with shorter expressions over lengthy selectors

### ISSUE THREAD

**Issue by sadeesh-sdet** [tejaswinidevi/ParaBank#6]
There are chances the tests will be brittle, if we use the lengthy selectors like [this](https://github.com/tejaswinidevi/ParaBank/blob/master/src/test/java/com/paraBanking/stepDefinitions/ParaBankStepDefinitions.java#L93). Check [this](https://www.testim.io/blog/understanding-xpath/) out.

**Comment by tejaswinidevi** [comment]
This issue is fixed. Changed all relative xpaths (browser generated) to xpaths that are customised using //tagName[attribute,value] format
