### ISSUE TITLE
Not all the transaction detail table fields are validated

### ISSUE THREAD

**Issue by sadeesh-sdet** [tejaswinidevi/ParaBank#7]
For Good Test Coverage, all the fields (ex: Date) and level of information (ex: Entire transaction history) in the table below to be validated but I see this is missing! Also, if we implement an efficient approach like [this](https://sqa.stackexchange.com/a/41126), it will save the execution time.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/87024075/209034604-76e8ff05-e560-4fe7-9d6e-c818e88c7668.png">

**Comment by tejaswinidevi** [comment]
added checks/validations for all the fields in transaction table
