### ISSUE TITLE
Listen to IDE Warnings/Problems for better code

### ISSUE THREAD

**Issue by sadeesh-sdet** [tejaswinidevi/ParaBank#8]
Listen to IDE Warnings/Problems for better code. 

This is belongs to one of your implementation!

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/87024075/209035907-08ad5ef1-2b31-49bb-81ed-6b38acc583ab.png">

**Comment by tejaswinidevi** [comment]
check IDE comments and removed unwanted and unused variables
